name: ci-cd
on:
  push:
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"
      - "CHANGELOG.md"
      - "LICENSE"
      - ".gitignore"
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      LEIN_ROOT: "true"
      CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
      CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.TEST_USER_MANAGER_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_USER_MANAGER_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.TEST_USER_MANAGER_AWS_DEFAULT_REGION }}
      TEST_USER_MANAGER_ROLE_ARN: ${{ secrets.TEST_USER_MANAGER_ROLE_ARN }}
      TEST_USER_MANAGER_COGNITO_USER_POOL_ID: ${{ secrets.TEST_USER_MANAGER_COGNITO_USER_POOL_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@5.1
        with:
          lein: 2.9.8

      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2020.04.05'

      - name: Check formatting
        run: lein cljfmt check

      - name: Lint
        run: clj-kondo --lint src --lint test && lein eastwood

      - name: Test
        run: lein test :all

      - name: Deploy Jar to Clojars
        if: contains(github.ref, 'refs/tags/')
        run: lein deploy
